//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interact
    {
        public int interactId { get; set; }
        public string uuid { get; set; }
        public int Customer_custId { get; set; }
        public int Employee_empId { get; set; }
    }
}
