//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interacts
    {
        public int interactId { get; set; }
        public int custId { get; set; }
        public int empId { get; set; }
        public string uuid { get; set; }
    
        public virtual Customers Customer { get; set; }
        public virtual Employees Employee { get; set; }
    }
}
