//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveysIn
    {
        public int surveyId { get; set; }
        public string uuid { get; set; }
        public string Reward { get; set; }
        public string Rating { get; set; }
    }
}
